#!/usr/bin/env bash
#
# A wizard — walks a human through deploying Forge to Railway.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Railway deployment
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Railway deployment"

# ── Stage 1: 创建 Railway 项目 ─────────────────────────────────────────────
stage "创建 Railway 项目"
say "Forge 部署为长驻单机（wayfinder ticket 14 的结论）：一个 web service + 一个 Postgres。"
open_url "https://railway.app/new"
step "选择「Deploy from GitHub repo」→ 授权 → 选 ttxs69/atoms-demo 仓库。"
step "Railway 会自动检测 Next.js 并创建 service。等构建完成（~2 分钟）。"
pause "项目创建好了？继续"

# ── Stage 2: 添加 Postgres ─────────────────────────────────────────────────
stage "添加 Postgres 数据库"
say "额度账本、GC 队列和封禁表都住在平台 Postgres 里。"
step "项目页面 → + Create → Database → Add PostgreSQL。"
step "等状态变为 Running（~30 秒）。"
step "点 Postgres 服务 → Variables 标签 → 找到 DATABASE_URL → 复制。"
ask DATABASE_URL "粘贴 DATABASE_URL（postgres://…）:"
pause "按 Enter 进入下一阶段"

# ── Stage 3: 设置环境变量 ──────────────────────────────────────────────────
stage "设置环境变量（全部从 .env 复制）"
say "Forge 的 web service 需要以下全部变量。在 Railway 的 web service → Variables 标签逐个添加。"
note "最快方式：如果你本地 .env 已配好，我可以生成一个可粘贴的 Raw 格式。"

if confirm "从本地 .env 生成 Raw 格式（一次粘贴全部变量）？"; then
  note "以下内容已复制到剪贴板（macOS）："
  # 排除 DATABASE_URL（Railway 自带）、注释行和空行
  RAW_ENV=$(grep -E "^[A-Z]" .env | grep -v "^DATABASE_URL=")
  if command -v pbcopy >/dev/null 2>&1; then
    printf '%s\n' "$RAW_ENV" | pbcopy
    say "✓ 已复制！到 Railway → Variables → Raw Editor → 粘贴 → Update"
  else
    say "手动复制以下内容："
    printf '\n%s\n' "$RAW_ENV"
  fi
  note "⚠ 别忘了也加上 NEXT_PUBLIC_SUPABASE_URL 和 NEXT_PUBLIC_SUPABASE_ANON_KEY（浏览器端需要）"
else
  step "逐个添加以下变量（从本地 .env 复制值）："
  for VAR in E2B_API_KEY LLM_PROTOCOL LLM_BASE_URL LLM_MODEL LLM_API_KEY \
    SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SECRET_KEY \
    NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY \
    TURNSTILE_SITE_KEY TURNSTILE_SECRET_KEY \
    APPS_SUPABASE_URL APPS_SUPABASE_PUBLISHABLE_KEY APPS_SUPABASE_SECRET_KEY APPS_SUPABASE_DB_URL \
    ADMIN_TOKEN DAILY_CAP TOKENS_PER_POINT RESERVE_ESTIMATE_TOKENS; do
    VAL=$(_existing "$VAR" || echo "")
    if [[ -n "$VAL" ]]; then
      note "  $VAR=<已配置>"
    else
      warn "  $VAR=未配置"
    fi
  done
fi

# 写 DATABASE_URL 到本地 .env（Railway Postgres 的连接串）
if [[ -n "${DATABASE_URL:-}" ]] && [[ "$DATABASE_URL" != *"e2b"* ]]; then
  write_env DATABASE_URL "$DATABASE_URL"
fi

pause "环境变量都设好了？继续"

# ── Stage 4: 部署 ──────────────────────────────────────────────────────────
stage "触发部署"
say "环境变量设完后 Railway 自动触发一次部署。如果没有："
step "web service → Settings → Deploy → Manual Deploy → Deploy Latest Commit。"
step "等构建+启动完成（首次 ~3 分钟）。"
step "查看 Deployments 标签确认状态为 ✓ Success。"
pause "部署成功？继续"

# ── Stage 5: 生成域名 ──────────────────────────────────────────────────────
stage "生成公开域名"
say "这是陌生人访问的入口。"
step "web service → Settings → Networking → Generate Domain。"
step "选一个子域名（如 forge.up.railway.app）或绑定自定义域名。"
ask RAILWAY_DOMAIN "你的域名是什么（如 forge.up.railway.app）:"
pause "按 Enter 进入下一阶段"

# ── Stage 6: 部署后验证 ────────────────────────────────────────────────────
stage "部署后验证"
say "在浏览器打开你的域名，走以下自检："

if [[ -n "${RAILWAY_DOMAIN:-}" ]]; then
  open_url "https://$RAILWAY_DOMAIN"
fi

step "1. 空状态出现（想做点什么？+ 三个样例）——前端渲染 OK"
step "2. 顶栏显示「升级保存」而非「连接中…」——Supabase 匿名登录 OK"
step "3. 说一句「做个计数器」→ 生成 → 预览出现——全链路 OK"
step "4. curl -H 'Authorization: Bearer <ADMIN_TOKEN>' https://$RAILWAY_DOMAIN/api/admin ——管理面板 OK"

printf '\n'
note "如果步骤 2 失败：检查 NEXT_PUBLIC_SUPABASE_URL 是否已设（浏览器端需要）。"
note "如果步骤 3 失败：查看 Railway 的 web service 日志，看 E2B_API_KEY / LLM_API_KEY 是否生效。"

pause "全部通过？部署完成！"

finish
