#!/usr/bin/env bash
#
# A wizard — walks a human through the Forge MVP's manual setup:
# platform Supabase project, shared Supabase project, Turnstile, admin
# token, quota knobs. Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Forge MVP credential setup
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Forge MVP setup"

# ── Stage 1: 平台 Supabase 项目（Forge 自己的账号/额度系统）────────────────
stage "平台 Supabase 项目（Forge 账号系统）"
say "建第一个项目。它只服务 Forge 自己的匿名登录、升级与额度——与生成应用的数据完全无关。"
open_url "https://supabase.com/dashboard/new"
step "项目名填 forge-platform，选个区域，设一个数据库密码（不需要记，我们不用这个库）。"
step "等状态变为 ACTIVE（约 1-2 分钟），进入项目。"
pause "项目建好了？继续"
step "开启匿名登录：左侧 Authentication → Sign In / Providers（旧版叫 Providers）→ Anonymous → 打开开关 → Save。"
step "取凭据：Project Settings（齿轮）→ API（新版叫 API Keys）。"
step "复制 Project URL（形如 https://xxx.supabase.co）。"
ask SUPABASE_URL "粘贴 Project URL:"
step "复制 publishable / anon key（标记为 publishable 或 anon public）。"
ask_secret SUPABASE_ANON_KEY "粘贴 anon(publishable) key:"
step "复制 secret / service_role key（标记为 secret 或 service_role——点 Reveal）。"
ask_secret SUPABASE_SECRET_KEY "粘贴 secret(service_role) key:"
say "前端还需要同一对值的 NEXT_PUBLIC_ 版本（构建时注入浏览器侧）。"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
write_env NEXT_PUBLIC_SUPABASE_URL "$SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
pause "按 Enter 进入下一阶段"

# ── Stage 2: 共享 Supabase 项目（生成应用的数据）────────────────────────────
stage "共享 Supabase 项目（生成应用数据）"
say "建第二个项目。所有生成应用的数据都住这里，靠 RLS 按 workspace 隔离。"
open_url "https://supabase.com/dashboard/new"
step "项目名填 forge-apps，建好后进入。"
pause "项目建好了？继续"
step "同样开启匿名登录：Authentication → Providers → Anonymous → 开 → Save（生成应用的登录用）。"
step "Project Settings → API：复制 Project URL。"
ask APPS_SUPABASE_URL "粘贴 Project URL:"
step "复制 publishable/anon key（生成代码里用的就是它，本来就是给前端的）。"
ask_secret APPS_SUPABASE_PUBLISHABLE_KEY "粘贴 publishable key:"
step "复制 secret/service_role key。"
ask_secret APPS_SUPABASE_SECRET_KEY "粘贴 secret key:"
step "取数据库连接串：Project Settings → Database → Connect（或 Connection string）。"
warn "不要用 db.<项目ref>.supabase.co 开头的 Direct connection —— 新项目已不解析该域名。"
step "选 Session pooler 标签（主机形如 aws-0-<区域>.pooler.supabase.com:5432，用户名形如 postgres.<项目ref>）。"
step "把 [YOUR-PASSWORD] 换成你建项目时设的数据库密码（忘了就在同一页 Reset database password）。"
ask_secret APPS_SUPABASE_DB_URL "粘贴完整连接串（含密码）:"
write_env APPS_SUPABASE_URL "$APPS_SUPABASE_URL"
write_env APPS_SUPABASE_PUBLISHABLE_KEY "$APPS_SUPABASE_PUBLISHABLE_KEY"
write_env APPS_SUPABASE_SECRET_KEY "$APPS_SUPABASE_SECRET_KEY"
write_env APPS_SUPABASE_DB_URL "$APPS_SUPABASE_DB_URL"
pause "按 Enter 进入下一阶段"

# ── Stage 3: Cloudflare Turnstile ─────────────────────────────────────────
stage "Cloudflare Turnstile（人机验证）"
say "免费层、无限挑战。挡住匿名端点的脚本滥用。"
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Add site → 域名填 localhost（上线后再加生产域名）→ Widget Mode 选 Invisible → Create。"
step "复制 Site Key。"
ask TURNSTILE_SITE_KEY "粘贴 Site Key:"
step "复制 Secret Key。"
ask_secret TURNSTILE_SECRET_KEY "粘贴 Secret Key:"
write_env TURNSTILE_SITE_KEY "$TURNSTILE_SITE_KEY"
write_env TURNSTILE_SECRET_KEY "$TURNSTILE_SECRET_KEY"
pause "按 Enter 进入下一阶段"

# ── Stage 4: ADMIN_TOKEN（脚本生成）────────────────────────────────────────
stage "ADMIN_TOKEN"
say "管理面板的单 token——脚本直接生成，无需浏览器。"
if command -v openssl >/dev/null 2>&1; then
  ADMIN_TOKEN=$(openssl rand -hex 24)
else
  ADMIN_TOKEN=$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')
fi
write_env ADMIN_TOKEN "$ADMIN_TOKEN"
note "你的 token（也保存在 .env 里）："
printf '  %s%s%s\n' "$BOLD" "$ADMIN_TOKEN" "$RESET"
note "访问管理面板：curl -H \"Authorization: Bearer <token>\" http://localhost:3000/api/admin"
pause "按 Enter 进入下一阶段"

# ── Stage 5: 额度参数（可选，回车用默认）──────────────────────────────────
stage "额度参数（可全用默认）"
say "内部 token 计量、对外点数展示。不确定就全部回车。"
ask DAILY_CAP "每人每日点数上限 [默认 100]:"
[[ -z "$DAILY_CAP" ]] && DAILY_CAP=100
ask TOKENS_PER_POINT "每点对应 token 数 [默认 10000]:"
[[ -z "$TOKENS_PER_POINT" ]] && TOKENS_PER_POINT=10000
ask RESERVE_ESTIMATE_TOKENS "生成前预扣的保守 token 估计 [默认 3000]:"
[[ -z "$RESERVE_ESTIMATE_TOKENS" ]] && RESERVE_ESTIMATE_TOKENS=3000
write_env DAILY_CAP "$DAILY_CAP"
write_env TOKENS_PER_POINT "$TOKENS_PER_POINT"
write_env RESERVE_ESTIMATE_TOKENS "$RESERVE_ESTIMATE_TOKENS"
pause "按 Enter 进入收尾"

# ── Stage 6: 收尾 ─────────────────────────────────────────────────────────
stage "收尾核对"
say "全部凭据已写入 .env（该文件被 git 忽略，永不入库）。"
note "已配置：E2B、LLM（之前已就位）+ 本轮的平台/共享 Supabase、Turnstile、ADMIN_TOKEN、额度。"
say "重启开发服务器使新变量生效："
printf '  %snpm run dev%s\n' "$BOLD" "$RESET"
say "快速自检（服务器跑起来后）："
step "浏览器打开 http://localhost:3000 —— 顶栏应显示「升级保存」而非「连接中…」（匿名登录通了）"
step "curl -H \"Authorization: Bearer $ADMIN_TOKEN\" http://localhost:3000/api/admin —— 返回 JSON（面板通了）"
step "说一句「做个待办清单，数据要保存」——生成走完且预览可点（全链路通了）"
printf '\n'
pause "完成"

finish
